# Generated by Django 3.0.2 on 2020-02-02 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
    ]
