# Generated by Django 3.0.2 on 2020-02-02 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 2, 2, 12, 46, 35, 781108, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('description', models.TextField()),
                ('sample_answer', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 2, 2, 12, 46, 35, 747416, tzinfo=utc))),
            ],
        ),
    ]
