# Generated by Django 3.0.2 on 2020-02-03 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_addinput_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyep', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='addinput',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addinput',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 13, 47, 43, 786495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 13, 47, 43, 754927, tzinfo=utc)),
        ),
    ]
