# Generated by Django 3.0.2 on 2020-02-22 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_auto_20200222_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 2, 22, 11, 13, 12, 862426, tzinfo=utc)),
        ),
    ]
