# Generated by Django 3.0.2 on 2020-02-27 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_auto_20200222_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 2, 27, 11, 33, 0, 513364, tzinfo=utc)),
        ),
    ]
