# Generated by Django 3.0.2 on 2020-03-07 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_auto_20200227_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 7, 9, 22, 25, 986115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
