# Generated by Django 3.0.2 on 2020-03-09 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0012_auto_20200308_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 9, 13, 54, 43, 485634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
