# Generated by Django 3.0.2 on 2020-03-09 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0013_auto_20200309_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 9, 13, 55, 59, 861966, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
